<a href="https://colab.research.google.com/github/SantoshMahara/Random_forest-Projects/blob/main/Census_Income_Project_10_March_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Census-Income Project**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('/content/sample_data/census-income .csv')

In [4]:
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,annual_income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [5]:
#Baisc info from dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64
 11  capital-loss    32561 non-null  int64
 12  hours-per-week  32561 non-null  int64
 13  native-country  32561 non-null  object
 14  annual_income   32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

**Data Preprocessing**
1. Checking for null values
2. Chcking duplicates
3. dealt with '?'
4. Statistical analysis of data
5. Encoding of categorical columns

In [6]:
#Check for null values
df.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
annual_income     0
dtype: int64

In [7]:
df.duplicated().sum()

24

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.duplicated().sum()

0

**Checking Unique values in workclass column**

In [10]:
df['workclass'].unique()

array(['State-gov', 'Self-emp-not-inc', 'Private', 'Federal-gov',
       'Local-gov', '?', 'Self-emp-inc', 'Without-pay', 'Never-worked'],
      dtype=object)

In [11]:
df['education'].unique()

array(['Bachelors', 'HS-grad', '11th', 'Masters', '9th', 'Some-college',
       'Assoc-acdm', 'Assoc-voc', '7th-8th', 'Doctorate', 'Prof-school',
       '5th-6th', '10th', '1st-4th', 'Preschool', '12th'], dtype=object)

In [12]:
df=df.replace('?',np.nan)

In [13]:
df.isna().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     582
annual_income        0
dtype: int64

In [14]:
df=df.dropna()

In [15]:
df.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
annual_income     0
dtype: int64

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30139 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             30139 non-null  int64
 1   workclass       30139 non-null  object
 2   fnlwgt          30139 non-null  int64
 3   education       30139 non-null  object
 4   education-num   30139 non-null  int64
 5   marital-status  30139 non-null  object
 6   occupation      30139 non-null  object
 7   relationship    30139 non-null  object
 8   race            30139 non-null  object
 9   sex             30139 non-null  object
 10  capital-gain    30139 non-null  int64
 11  capital-loss    30139 non-null  int64
 12  hours-per-week  30139 non-null  int64
 13  native-country  30139 non-null  object
 14  annual_income   30139 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [18]:
df.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,30139.000000,3.013900e+04,30139.000000,30139.000000,30139.000000,30139.000000
mean,38.441720,1.897950e+05,10.122532,1092.841202,88.439928,40.934703
std,13.131426,1.056586e+05,2.548738,7409.110596,404.445239,11.978753
min,17.000000,1.376900e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.176275e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.784170e+05,10.000000,0.000000,0.000000,40.000000
75%,47.000000,2.376045e+05,13.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [20]:
df.describe(include='O').T

                count unique                 top   freq
workclass       30139      7             Private  22264
education       30139     16             HS-grad   9834
marital-status  30139      7  Married-civ-spouse  14059
occupation      30139     14      Prof-specialty   4034
relationship    30139      6             Husband  12457
race            30139      5               White  25912
sex             30139      2                Male  20366
native-country  30139     41       United-States  27487
annual_income   30139      2               <=50K  22633

**Label Encoding**

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
LE=LabelEncoder()

In [24]:
for col in df.columns:
  if df[col].dtype=='object':
   df[col]= LE.fit_transform(df[col])

In [25]:
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,annual_income
0,39,5,77516,9,13,4,0,1,4,1,2174,0,40,38,0
1,50,4,83311,9,13,2,3,0,4,1,0,0,13,38,0
2,38,2,215646,11,9,0,5,1,4,1,0,0,40,38,0
3,53,2,234721,1,7,2,5,0,2,1,0,0,40,38,0
4,28,2,338409,9,13,2,9,5,2,0,0,0,40,4,0

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30139 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             30139 non-null  int64
 1   workclass       30139 non-null  int64
 2   fnlwgt          30139 non-null  int64
 3   education       30139 non-null  int64
 4   education-num   30139 non-null  int64
 5   marital-status  30139 non-null  int64
 6   occupation      30139 non-null  int64
 7   relationship    30139 non-null  int64
 8   race            30139 non-null  int64
 9   sex             30139 non-null  int64
 10  capital-gain    30139 non-null  int64
 11  capital-loss    30139 non-null  int64
 12  hours-per-week  30139 non-null  int64
 13  native-country  30139 non-null  int64
 14  annual_income   30139 non-null  int64
dtypes: int64(15)
memory usage: 3.7 MB

In [29]:
ol=LE.classes_
for label, value in enumerate(ol):
print (label , values)

IndentationError: expected an indented block after 'for' statement on line 2 (<ipython-input-29-cf8cc83c65c1>, line 3)

**Separate Independent and Dependent Features**

In [32]:
X=df.iloc[:,:-1]
Y=df.iloc[:, -1]

In [36]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(X,Y,test_size=0.3, random_state=56)

In [37]:
x_train

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
31616,28,2,187397,11,9,4,7,2,3,1,0,0,48,25
20471,40,2,442045,15,10,2,9,0,4,1,0,0,40,38
247,32,2,183916,11,9,4,7,1,4,0,0,0,34,38
30454,36,2,255454,11,9,4,2,3,2,1,0,0,30,38
9122,34,2,202210,11,9,4,7,4,2,0,0,0,40,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27890,33,4,109959,15,10,2,11,0,4,1,0,0,25,38
14831,48,3,302612,12,14,2,7,0,4,1,0,0,40,38
3554,23,2,60847,8,11,4,11,4,4,0,0,0,60,38
429,47,1,287480,12,14,2,9,0,4,1,0,0,40,38
2762,51,2,234057,11,9,2,2,0,4,1,0,0,45,38

In [38]:
x_test

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
4140,43,5,125405,11,9,2,10,0,4,1,0,0,40,38
8639,31,2,200192,11,9,0,0,1,4,0,0,0,40,10
24350,43,2,247162,7,12,4,11,3,4,1,0,0,40,38
16467,25,2,278404,9,13,4,9,1,4,1,0,0,40,38
20870,44,1,193882,8,11,4,12,1,4,1,0,1340,40,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2989,44,2,178385,12,14,2,3,0,1,1,0,0,48,18
29602,18,2,122775,11,9,4,7,3,4,1,0,0,35,38
26733,24,1,84257,9,13,4,9,1,4,1,0,0,50,38
25503,48,2,287480,12,14,2,12,0,4,1,0,0,40,38
29572,27,1,162404,11,9,4,10,1,2,1,2174,0,40,38

In [39]:
x_test

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
4140,43,5,125405,11,9,2,10,0,4,1,0,0,40,38
8639,31,2,200192,11,9,0,0,1,4,0,0,0,40,10
24350,43,2,247162,7,12,4,11,3,4,1,0,0,40,38
16467,25,2,278404,9,13,4,9,1,4,1,0,0,40,38
20870,44,1,193882,8,11,4,12,1,4,1,0,1340,40,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2989,44,2,178385,12,14,2,3,0,1,1,0,0,48,18
29602,18,2,122775,11,9,4,7,3,4,1,0,0,35,38
26733,24,1,84257,9,13,4,9,1,4,1,0,0,50,38
25503,48,2,287480,12,14,2,12,0,4,1,0,0,40,38
29572,27,1,162404,11,9,4,10,1,2,1,2174,0,40,38

In [40]:
y_train

31616    0
20471    1
247      0
30454    0
9122     0
        ..
27890    0
14831    0
3554     0
429      0
2762     1
Name: annual_income, Length: 21097, dtype: int64

In [41]:
y_test

4140     0
8639     0
24350    0
16467    0
20870    0
        ..
2989     0
29602    0
26733    0
25503    1
29572    0
Name: annual_income, Length: 9042, dtype: int64

#Standardization

In [42]:
from sklearn.preprocessing import StandardScaler

In [49]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

**Model Building -1 Logistic Regression**

In [50]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

In [51]:
y_pred=model.predict(x_test)

In [52]:
y_pred

array([0, 0, 0, ..., 0, 1, 0])

In [48]:
from sklearn.metrics import *

In [53]:
accuracy=accuracy_score(y_test, y_pred)

In [54]:
accuracy

0.825149303251493

In [55]:
confusion_matrix(y_test,y_pred)

array([[6413,  366],
       [1215, 1048]])

In [56]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.95      0.89      6779
           1       0.74      0.46      0.57      2263

    accuracy                           0.83      9042
   macro avg       0.79      0.70      0.73      9042
weighted avg       0.82      0.83      0.81      9042

**Model Building-2 using Random Forest**

In [58]:
from sklearn.ensemble import RandomForestClassifier

In [60]:
model2=RandomForestClassifier()
model2.fit(x_train,y_train)

RandomForestClassifier()

In [61]:
y_pred2=model2.predict(x_test)
y_pred2

array([0, 0, 0, ..., 0, 1, 0])

In [62]:
accuracy2=accuracy_score(y_test, y_pred2)
accuracy2

0.8595443485954435

In [63]:
confusion_matrix(y_test,y_pred2)

array([[6325,  454],
       [ 816, 1447]])

In [64]:
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.89      0.93      0.91      6779
           1       0.76      0.64      0.70      2263

    accuracy                           0.86      9042
   macro avg       0.82      0.79      0.80      9042
weighted avg       0.85      0.86      0.86      9042

**Model Building -3**

In [65]:
from sklearn.tree import DecisionTreeClassifier

In [66]:
model3=DecisionTreeClassifier()
model3.fit(x_train,y_train)

DecisionTreeClassifier()

In [70]:
y_pred3=model3.predict(x_test)

In [71]:
accuracy=accuracy_score(y_test, y_pred3)
accuracy

0.8038044680380447